"""Sanity tests for the KNOWN_STUDIOS tuple in const.py.

The list is regenerated by scripts/discover_studios.py (which runs weekly
in CI and opens a PR on change). These invariants catch obvious mistakes
before the list lands in a release.
"""
from __future__ import annotations

from custom_components.bsport.const import KNOWN_STUDIOS


def test_studio_ids_are_positive_integers() -> None:
    for cid, _name in KNOWN_STUDIOS:
        assert isinstance(cid, int), f"non-int id: {cid!r}"
        assert cid > 0, f"non-positive id: {cid}"


def test_studio_ids_are_unique() -> None:
    ids = [cid for cid, _ in KNOWN_STUDIOS]
    dupes = {i for i in ids if ids.count(i) > 1}
    assert not dupes, f"duplicate ids: {sorted(dupes)}"


def test_studio_names_are_non_empty_strings() -> None:
    for cid, name in KNOWN_STUDIOS:
        assert isinstance(name, str), f"non-str name for id {cid}: {name!r}"
        assert name.strip(), f"empty / whitespace-only name for id {cid}"


def test_studios_are_sorted_by_id() -> None:
    ids = [cid for cid, _ in KNOWN_STUDIOS]
    assert ids == sorted(ids), (
        "KNOWN_STUDIOS must be sorted by id for stable diffs in auto-update PRs; "
        "re-run scripts/discover_studios.py --update-const to fix"
    )


def test_includes_the_two_seed_studios() -> None:
    """Chimosa and Mindful Life Berlin are the reference studios the
    integration was originally developed and validated against; they must
    stay in the list across scraper regenerations."""
    ids = {cid for cid, _ in KNOWN_STUDIOS}
    assert 538 in ids, "Chimosa (id 538) missing from KNOWN_STUDIOS"
    assert 2387 in ids, "Mindful Life Berlin (id 2387) missing from KNOWN_STUDIOS"


def test_config_flow_options_are_alphabetical_with_other_last() -> None:
    """The dropdown presentation sorts studios by name (case-insensitive)
    so the list reads like a directory. The 'Other' escape-hatch stays
    pinned at the bottom regardless of alphabetization."""
    from custom_components.bsport.config_flow import (
        STUDIO_OTHER_SENTINEL,
        _STUDIO_OPTIONS,
    )

    # Last entry is always the escape hatch.
    assert _STUDIO_OPTIONS[-1]["value"] == STUDIO_OTHER_SENTINEL

    studio_labels = [opt["label"] for opt in _STUDIO_OPTIONS[:-1]]
    expected = sorted(studio_labels, key=str.casefold)
    assert studio_labels == expected, (
        "studios must be ordered alphabetically (case-insensitive) in the "
        "config-flow dropdown"
    )

    # Known anchors show up in the expected alphabetical neighbourhood —
    # "Chimosa" before anything starting with "D", "Mindful Life Berlin"
    # in the M's.
    assert "Chimosa" in studio_labels
    assert "Mindful Life Berlin" in studio_labels
